### ISSUE TITLE
AskResult bindingSet different from exchangeInfo bindingSet

### ISSUE THREAD

**Issue by johankumps** [TNO/knowledge-engine#506] opened 2024-05-23 14:13 UTC
Hello,

It seeams the the bindingSet retrieved via askResult.getBindingSet is different from askResult.getExchangeInfo..get(0).getBindingSet().
More specifically the datatype of a literal is not present in askResult.getBindingSet. Is there a reason for this?

Please consider folowing print screen of my debugging session 

![image](https://github.com/TNO/knowledge-engine/assets/6989115/1be99280-1e97-4b22-bbd9-36ee018866f9)

**Comment by bnouwt** [comment] 2024-05-24 07:01
Hey @johankumps, good catch! That is definitely not intended. I think it is a bug in [this code](https://github.com/TNO/knowledge-engine/blob/master/smart-connector/src/main/java/eu/knowledge/engine/smartconnector/impl/GraphPatternMatcher.java#L164).

Thanks for reporting!

**Comment by bnouwt** [comment] 2024-05-27 15:17
@johankumps I am trying to reproduce the behavior described above so that I can start solving the issue, but have not succeeded yet. Both via the Java API and the REST API the datatype of a literal shows up in both the merged binding set as well as the knowledge base specific binding set. Do you have additional information for me? 

The screenshot of the debugging session confuses me a little bit because both `bindingSet` variables have the `ArrayList` type, while in reality they are of type `HashSet`. Are you using the latest version (`1.2.4`) of the Knowledge Engine? Maybe you can double check what happens if you actually print the values of the `isWithin` binding to the console, to make sure the datatype is indeed not there?

**Comment by johankumps** [comment] 2024-05-29 07:03
Hello Barry, I'm not using the latest version 1.2.4. I'm using 1.2.1. I'll upgrade my knowledge engine instance first and retest my scenario.

**Comment by johankumps** [comment] 2024-05-29 10:31
I upgraded my KE to 1.2.4. After some issues with the REST client generation I'm able to call the KE from within my code. I execute the scAskPost with no recipientSelector. Only a bindingSet in the ScAskPostRequest instance used as parameter for the ProactiveAPI.scAskPost method. I keep getting this error : The RecipientSelector should be a valid JSON object with a singleKnowledgeBase key that leads to a string value of a KnowledgeBaseId.

**Comment by bnouwt** [comment] 2024-05-29 15:11
Thanks for the info. The `POST /sc/ask` [operation](https://github.com/TNO/knowledge-engine/blob/1.2.4/smart-connector-rest-server/src/main/resources/openapi-sc.yaml#L299-L301) support two different `requestBody` JSON objects; only a binding set or a recipient selector with a binding set. If you choose the latter, it seems like you cannot leave the recipient selector empty (by `null` or `{}`) like you do above. Does the generated `ScAskPostRequest` object allows you to provide an empty list of knowledge bases which results in the following JSON:

```
{
	"recipientSelector": {
		"knowledgeBases": []
	},
	"bindingSet": [
		{
			"geometry": "http://example.org/ontology#someGeometry"
		},
		{
			"foi": "http://example.org/ontology#myFoi"
		}
	]
}
```
I have tested the above and it works. Alternatively, you can use the binding set only option and make sure the JSON looks like this:
```
[
	{
		"geometry": "http://example.org/ontology#someGeometry"
	},
	{
		"foi": "http://example.org/ontology#myFoi"
	}
]
```

Hope this helps! 👍 

Regards, Barry

**Comment by johankumps** [comment] 2024-05-29 20:47
After adding an empty knowledgebases list to the recipientselector it seems to work but unfortunately the bindingset is still different on the level of the datatype:

result.getBindingSet().get(0).get("isWithin") :: true
result.getExchangeInfo().get(0).getBindingSet().get(0).get("isWithin") :: "true"^^<http://www.w3.org/2001/XMLSchema#boolean>

I'm currently using the 1.2.4 version.

**Comment by bnouwt** [comment] 2024-05-30 07:49
> unfortunately the bindingset is still different on the level of the datatype
That's a pity. Would it be possible to provide a code example to which I have access that shows the problem in action so I can at least reproduce it?

> Where should I see the HashSet?
My mistake, I was mixing up your generated Java client/API with the Knowledge Engine's Java API that. Do you maybe have access to the JSON response from the Knowledge Engine in your generated Java client? This way we can rule out that the problem occurs within the generated Java client.

**Comment by johankumps** [comment] 2024-05-30 17:21
I've intercepted the request and response messages:

Request:

`{"recipientSelector":{"knowledgeBases":[]},"bindingSet":[{"geometry":"<http://example.org/ontology#someGeometry>"},{"foi":"<http://example.org/ontology#myFoi>"}]}`

Response : 

`HTTP/1.1 200 OK
Date: Thu, 30 May 2024 17:17:00 GMT
Content-Type: application/json;charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, HEAD
Access-Control-Allow-Headers: Accept, Content-Type, Knowledge-Base-Id, Knowledge-Interaction-Id
Content-Length: 697
Server: Jetty(11.0.15)

{"bindingSet":[{"foi":"<http://example.org/ontology#myFoi>","geometry":"<http://example.org/ontology#someGeometry>","isWithin":"true"}],"exchangeInfo":[{"initiator":"knowledgeBase","knowledgeBaseId":"https://world.inetum/khc-gw/service/sparql-endpoint-adapter","knowledgeInteractionId":"https://world.inetum/khc-gw/service/sparql-endpoint-adapter/interaction/1a54e939-74ed-4ed5-8117-3b390bf00f75","exchangeStart":"2024-05-30T17:17:00.582+00:00","exchangeEnd":"2024-05-30T17:17:00.865+00:00","status":"SUCCEEDED","bindingSet":[{"foi":"<http://example.org/ontology#myFoi>","geometry":"<http://example.org/ontology#someGeometry>","isWithin":"\"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>"}]}]}`

**Comment by bnouwt** [comment] 2024-05-30 19:47
Thanks! I notice that in your response the typed literal in the exchange info is incorrect; instead of `""true"^^http://www.w3.org/2001/XMLSchema#boolean"` it should look like `"\"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>`. Notice the slashes (`\`) before the double quotes and the angled brackets (`<` and `>`) around the type. Can you, by any chance, show the JSON binding set of the KB that provides the typed literal? I might be able to reproduce this behavior if I see how the binding set where the `isWithin` boolean value is provided.

**Comment by johankumps** [comment] 2024-05-30 21:03
The bindingset (as JSON) being returned : 

`[
   {
      "foi":"<http://example.org/ontology#myFoi>",
      "geometry":"<http://example.org/ontology#someGeometry>",
      "isWithin":"\"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>"
   }
]`

**Comment by bnouwt** [comment] 2024-05-31 07:21
Aha, thanks. Some additional questions:
- Can you post the graph pattern with the `?foi`, '?geometry` and `isWithin` variables?
- Can you double check if the escaped quotes and angled brackets are indeed missing, or whether those were somehow lost during the copy/paste process to github?
- Does this problem also occur when you execute the scenario using Postman or CURL instead of using the generated Java client?

And just to be clear about the scenario:

- You have a KB1 that has an ANSWER KI which returns the following binding set on request:

```
[
	{
		"foi": "<http://example.org/ontology#myFoi>",
		"geometry": "<http://example.org/ontology#someGeometry>",
		"isWithin": "\"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>"
	}
]
```

  - You have a KB2 that has an ASK KI that asks with the following JSON:

```
{
	"recipientSelector": {
		"knowledgeBases": []
	},
	"bindingSet": [
		{
			"geometry": "<http://example.org/ontology#someGeometry>"
		},
		{
			"foi": "<http://example.org/ontology#myFoi>"
		}
	]
}
```

  - When you execute this ASK KI the following JSON is returned in which the typed literal in the exchange info is incorrectly quoted (missing escaped character) and is missing angled brackets and the type of the `true` value in the combined binding set is gone:

```
{
   "bindingSet":[
      {
         "foi":"http://example.org/ontology#myFoi",
         "geometry":"http://example.org/ontology#someGeometry",
         "isWithin":"true"
      }
   ],
   "exchangeInfo":[
      {
         "initiator":"knowledgeBase",
         "knowledgeBaseId":"https://world.inetum/khc-gw/service/sparql-endpoint-adapter",
         "knowledgeInteractionId":"https://world.inetum/khc-gw/service/sparql-endpoint-adapter/interaction/1a54e939-74ed-4ed5-8117-3b390bf00f75",
         "exchangeStart":"2024-05-30T17:17:00.582+00:00",
         "exchangeEnd":"2024-05-30T17:17:00.865+00:00",
         "status":"SUCCEEDED",
         "bindingSet":[
            {
               "foi":"http://example.org/ontology#myFoi",
               "geometry":"http://example.org/ontology#someGeometry",
               "isWithin":""true"^^http://www.w3.org/2001/XMLSchema#boolean"
            }
         ]
      }
   ]
}
```

**Comment by johankumps** [comment] 2024-05-31 10:22
- c
- The < and > are part of the response as you can see in the debugger screen shot above. Apparently this is a copy past issue to Github.
- Using PostMan/cUrl:

`curl --location 'http://localhost:8280/rest/sc/ask' \
--header 'Knowledge-Base-Id: https://world.inetum/khc-gw/service/knowledge-item-fetcher-reasoner' \
--header 'Knowledge-Interaction-Id: https://world.inetum/khc-gw/service/knowledge-item-fetcher-reasoner/interaction/f51ba4d8-495a-4c46-8d37-f0964c1d1749' \
--header 'Content-Type: application/json; charset=UTF-8' \
--header 'Accept: application/json; charset=UTF-8' \
--data '{
	"recipientSelector": {
		"knowledgeBases": []
	},
	"bindingSet": [
		{
			"geometry": "<http://example.org/ontology#someGeometry>"
		},
		{
			"foi": "<http://example.org/ontology#myFoi>"
		}
	]
}'`

`{
    "bindingSet": [
        {
            "foi": "<http://example.org/ontology#myFoi>",
            "geometry": "<http://example.org/ontology#someGeometry>",
            "isWithin": "true"
        }
    ],
    "exchangeInfo": [
        {
            "initiator": "knowledgeBase",
            "knowledgeBaseId": "https://world.inetum/khc-gw/service/sparql-endpoint-adapter",
            "knowledgeInteractionId": "https://world.inetum/khc-gw/service/sparql-endpoint-adapter/interaction/db773404-70f1-4cea-9f2d-daebc36cd9ac",
            "exchangeStart": "2024-05-31T10:21:19.588+00:00",
            "exchangeEnd": "2024-05-31T10:21:19.849+00:00",
            "status": "SUCCEEDED",
            "bindingSet": [
                {
                    "foi": "<http://example.org/ontology#myFoi>",
                    "geometry": "<http://example.org/ontology#someGeometry>",
                    "isWithin": "\"true\"^^<http://www.w3.org/2001/XMLSchema#boolean>"
                }
            ]
        }
    ]
}`

**Comment by bnouwt** [comment] 2024-05-31 11:12
Can you also post the graph pattern you are using?

**Comment by johankumps** [comment] 2024-05-31 11:27
The is the KI spec:

```
[
    {
        "knowledgeInteractionType": "AskKnowledgeInteraction",
        "communicativeAct": {
            "requiredPurposes": [
                "https://w3id.org/knowledge-engine/InformPurpose"
            ],
            "satisfiedPurposes": [
                "https://w3id.org/knowledge-engine/InformPurpose"
            ]
        },
        "prefixes": {},
        "graphPattern": "?foi <http://example.org/ontology#withinGeometry> ?geometry . ?foi <http://example.org/ontology#isWithin> ?isWithin . ",
        "knowledgeInteractionId": "https://world.inetum/khc-gw/service/knowledge-item-fetcher-reasoner/interaction/f51ba4d8-495a-4c46-8d37-f0964c1d1749"
    }
]
```

**Comment by bnouwt** [comment] 2024-05-31 12:04
I suddenly realize that I assumed you were *not* using the reasoner, but when I enable the reasoner I can immediately reproduce the behavior 👍 . Now we can take a look at what is going wrong. Thanks for your patience!

**Comment by johankumps** [comment] 2024-05-31 13:07
ASK side has reasoner enabled; ANSWER side no reasoner

**Closed** 2024-05-31 13:35 UTC
Labels: bug

**Comment by bnouwt** [comment] 2024-05-31 13:38
I [found the cause](https://github.com/TNO/knowledge-engine/pull/508/commits/2911abb74d861b6813c8af240dadc9347ad60f7f#diff-886a1302d57b9cd3f2339bbf74f427ee97909e291a532441d80782e05cce2112R274), but unfortunately, there is no work around. All typed literals were converted into [simple or plain literals](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) when they are converted into a string. I have fixed this behavior to *never* use plain literals for values in a binding set when converting them and this indeed solves the issue. I also added a unit test for this use case, so if we do a future rewrite this incorrect behavior will hopefully not sneak back in.

You have two options: either use the current SNAPSHOT version with the fix or wait for the next release (nothing planned yet). Is that workable for you?

**Comment by johankumps** [comment] 2024-05-31 14:37
I can indeed confirm that the issue is fixed on the current master branch. It's ok for me to use this for now. Looking forward to the new release. Will the lightning fast reasoner :) be in that release too?

**Comment by bnouwt** [comment] 2024-05-31 14:55
It might be. We am currently improving the so called [Graph Pattern matcher](https://github.com/TNO/knowledge-engine/blob/master/reasoner/src/main/java/eu/knowledge/engine/reasoner/BaseRule.java#L141) algorithm that is used in the reasoner to build the reasoning graph. This is currently the biggest bottleneck when using the reasoner with bigger graph patterns. We have some clear pointers on how to improve it, but It is still quite challenging 😄.
